######################################################################
# Automatically generated by qmake (3.1) Thu Jul 13 21:05:24 2023
######################################################################

TEMPLATE = app
TARGET = dynamicWidgets
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += forms/dynamicui.h
SOURCES += main.cpp \
           forms/dynamicui.cpp
